pipeline {
    agent any
    environment {
        NODE_ENV = 'production'
    }
    stages {
        stage('Checkout') {
            steps {
                // Git 리포지토리에서 소스 코드를 가져옵니다.
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                // 프로젝트 의존성 설치
                sh 'cd BE && npm install'
            }
        }
        stage('Build') {
            steps {
                // NestJS 애플리케이션 빌드
                sh 'cd BE && npm run build'
            }
        }
        stage('Test') {
            steps {
                // 테스트 실행
                sh 'cd BE && npm run test'
            }
        }
        stage('Deploy') {
            steps {
                // pm2 로 배포 
                sh 'pm2 delete all'
                sh 'pm2 start BE/dist/main.js --name \'QLab Backend Server\''
            }
        }
    }
    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}