FROM node:20

WORKDIR /app/

RUN npm install -g pm2

COPY ./package*.json /app

RUN npm install

WORKDIR /app/BE/

COPY ./BE/package*.json /app/BE/

RUN npm install

COPY ./BE /app/BE

COPY ./schemas /app/schemas

CMD npm run test && npm run build